package com.example.flutter_app

import android.accessibilityservice.AccessibilityService
import android.view.KeyEvent
import android.view.accessibility.AccessibilityEvent
import android.util.Log

class KavachAccessibilityService : AccessibilityService() {
    private val eventBuffer = mutableListOf<Pair<Int, Long>>()
    private val PATTERN_WINDOW_MS: Long = 2000
    
    override fun onKeyEvent(event: KeyEvent): Boolean {
        val keyCode = event.keyCode
        val action = event.action

        // We listen for ACTION_DOWN (press)
        if (action == KeyEvent.ACTION_DOWN) {
            // Ignore events generated by holding the button (auto-repeat)
            if (event.repeatCount > 0) return false

            val currentTime = System.currentTimeMillis()
            
            if (keyCode == KeyEvent.KEYCODE_VOLUME_UP || keyCode == KeyEvent.KEYCODE_VOLUME_DOWN) {
                // Prune events older than the window (2000ms)
                eventBuffer.removeAll { currentTime - it.second > PATTERN_WINDOW_MS }
                
                // Add current event
                eventBuffer.add(Pair(keyCode, currentTime))
                Log.d("KavachAccess", "Key: ${if (keyCode == KeyEvent.KEYCODE_VOLUME_UP) "UP" else "DOWN"}, Buffer size: ${eventBuffer.size}")
                
                // Check for sequence: Up -> Down -> Down
                if (eventBuffer.size >= 3) {
                    val lastThree = eventBuffer.takeLast(3)
                    if (lastThree[0].first == KeyEvent.KEYCODE_VOLUME_UP && 
                        lastThree[1].first == KeyEvent.KEYCODE_VOLUME_DOWN && 
                        lastThree[2].first == KeyEvent.KEYCODE_VOLUME_DOWN) {
                        
                        Log.d("KavachAccess", "🚨 [NATIVE] SOS Pattern Matched (Up-Down-Down) within ${currentTime - lastThree[0].second}ms!")
                        eventBuffer.clear() // Prevent partial match and double trigger
                        
                        // Notify via plugin
                        KavachPlugin.getInstance().triggerSOSFromNative()
                    }
                }
            }
        }
        
        // Return false so we don't block the volume change (less suspicious/intrusive)
        return false
    }

    override fun onAccessibilityEvent(event: AccessibilityEvent?) {
        // Not needed for key interception
    }

    override fun onInterrupt() {
        Log.d("KavachAccess", "Service Interrupted")
    }
    
    override fun onServiceConnected() {
        super.onServiceConnected()
        Log.d("KavachAccess", "Kavach SOS Accessibility Service Connected")
    }
}
